# Generated by Django 5.1.6 on 2025-03-04 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_curso', to='lms.curso'),
        ),
        migrations.AddField(
            model_name='user',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='professores_curso', to='lms.curso'),
        ),
        migrations.AddField(
            model_name='user',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='users_materia', to='lms.materia'),
        ),
    ]
