# Generated by Django 5.1.6 on 2025-03-11 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_user_curso_user_cursos_user_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='materias',
        ),
    ]
