# Generated by Django 5.1.6 on 2025-03-05 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_entrega', models.DateField()),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'atividade',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('atividades', models.ManyToManyField(related_name='aulas_atividade', to='lms.atividade')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.materia')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'aula',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.aula'),
        ),
        migrations.AddField(
            model_name='materia',
            name='aulas',
            field=models.ManyToManyField(related_name='materias_aula', to='lms.aula'),
        ),
    ]
