# Generated by Django 5.1.6 on 2025-03-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='conteudo',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='aula',
            name='conteudo',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
