# Generated by Django 5.1.6 on 2025-03-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_remove_user_materias'),
        ('lms', '0004_atividade_conteudo_aula_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='materia',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='curso',
            name='materias',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='materia',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
